apiVersion: v1
kind: Service
metadata:
  name: {{ include "reversed-ip-app.fullname" . }}
  labels:
    {{- include "reversed-ip-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: web
  selector:
    {{- include "reversed-ip-app.selectorLabels" . | nindent 4 }}
