name: Docker Build & Deploy

on:
  push:
    branches:
      - dev

# Environment files.
env:
    RUN_REGION: europe-west3
    SERVICE_NAME: reversed-ip-app
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}
    CLUSTER_NAME: ${{secrets.CLUSTER }}
    CLUSTER_ZONE: ${{secrets.CLUSTER_ZONE }}
    APP_VERSION: latest # Default version, can be overridden

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/${{env.SERVICE_NAME}}:${{ github.sha }} .
      
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/${{env.SERVICE_NAME}}:${{ github.sha }}
      
  deploy:
    name: Deploy kube
    runs-on: ubuntu-latest  
    needs: [build]


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Configure Cloud SDK
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCLOUD_KEY }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      # Configure Cloud GKE SDK.
      - name: Setup GKE CLI
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Deploy to Kubernetes
        run: kubectl set image deployment ${{env.SERVICE_NAME}} -n dev ${{env.SERVICE_NAME}}=${{ env.DOCKER_USERNAME }}/${{env.SERVICE_NAME}}:${{ github.sha }}