name: Docker Build & Deploy

on:
  push:
    branches:
      - dev

# Environment files.
env:
    RUN_REGION: europe-west3
    SERVICE_NAME: reversed-ip-app
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/${{env.SERVICE_NAME}}:latest .
      
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/${{env.SERVICE_NAME}}:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install kubectl
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: install --kubectl-version=v1.23.0

      - name: Configure kubectl
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
      - name: Set kubeconfig permissions
        run: chmod 600 kubeconfig
      - name: Copy kubeconfig to its default location
        run: cp kubeconfig $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f helm-charts/${{env.SERVICE_NAME}}/templates/deployment.yaml
